version: "2.4"

services:
  prt-master:
    image: poludo/plex-remote-transcoder:master
    container_name: prt-master
    restart: unless-stopped
    privileged: true
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - /mnt/prt/master/config:/config
      - /mnt/prt/master/data:/data
    networks:
      prt-backend:
        ipv4_address: 172.20.0.2
  prt-slave:
    image: poludo/plex-remote-transcoder:slave
    container_name: prt-slave
    restart: unless-stopped
    privileged: true
    environment:
      - MASTER_IP=172.20.0.2
      - MASTER_NFS_PORT=2049
      - MASTER_SSH_PORT=22
      - SLAVE_SSH_PORT=22
    volumes:
      - /mnt/prt/slave/config:/config
    networks:
      prt-backend:
        ipv4_address: 172.20.0.3

networks:
  prt-backend:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16