#!/usr/bin/with-contenv sh

# Plex home directory
mkdir -p "/config"
chown -R plex:plex "/config"

# Plex config directory
mkdir -p "/var/lib/plexmediaserver"
chown -R plex:plex "/var/lib/plexmediaserver"

# Plex bin directory
mkdir -p "/usr/lib/plexmediaserver"
chown -R plex:plex "/usr/lib/plexmediaserver"

# Plex transcode directory
mkdir -p "/transcode"
chown -R plex:plex "/transcode"
