#!/usr/bin/with-contenv sh

if [ ! -f /config/.ssh/id_rsa ]; then
	# Generate the SSH key pair
	s6-setuidgid plex ssh-keygen -N '' -f ~/.ssh/id_rsa
	
	# Allow incoming ssh authentication using the generated private key
	s6-setuidgid plex mv ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys
	chmod 600 ~/.ssh/authorized_keys
	
	# Set up ssh controlmaster
	s6-setuidgid plex mkdir -p /config/.ssh/controlmasters
	chmod 700 /config/.ssh/controlmasters
	s6-setuidgid plex touch /config/.ssh/config
	chmod 600 /config/.ssh/config
fi
