#!/usr/bin/with-contenv sh

# Prepare exports of Plex related directories
mount --bind "/usr/lib/plexmediaserver" "/exports/plex_bin.d"
mount --bind "/config/Library/Application Support/Plex Media Server" "/exports/plex_conf.d"
mount --bind "/data" "/exports/plex_media.d"
mount --bind "/transcode" "/exports/plex_transcode.d"
