#!/usr/bin/with-contenv sh

# Prepare Plex config directory
mkdir -p "/exports/plex_conf.d"
mount --bind "/config/Library/Application Support/Plex Media Server" "/exports/plex_conf.d"

# Prepare Plex bin directory
mkdir -p "/exports/plex_bin.d"
mount --bind "/usr/lib/plexmediaserver" "/exports/plex_bin.d"

# Prepare Plex transcode directory
mkdir -p "/exports/plex_transcode.d"
mount --bind "/transcode" "/exports/plex_transcode.d"
