#!/usr/bin/with-contenv sh

if [ ! -f /config/.ssh/id_rsa -o ! -f /config/.ssh/authorized_keys ]; then
	echo ""
	echo "|-----------------------------------------------------------------------------------------------|"
	echo "|                                                                                               |"
	echo "|                                 THE SSH DIRECTORY IS MISSING.                                 |"
	echo "|  Please import the '/config/.ssh' directory from the master node (by keeping the same path).  |"
	echo "|                                                                                               |"
	echo "|-----------------------------------------------------------------------------------------------|"
	echo ""
	exit 1
else
	# Set up ssh controlmaster
	printf "Host ${MASTER_IP}\n        User plex\n        Port ${MASTER_SSH_PORT}\n        ControlPath /config/.ssh/controlmasters/%%r@%%h:%%p\n        ControlMaster auto\n        ControlPersist 2h\n        StrictHostKeyChecking no\n" > /config/.ssh/config
	
	# Set permissions
	chown -R plex:plex /config/.ssh
	
	chmod 700 /config/.ssh
	chmod 700 /config/.ssh/controlmasters
	chmod 600 /config/.ssh/authorized_keys	
	chmod 600 /config/.ssh/config
	chmod 600 /config/.ssh/id_rsa
fi
