#!/usr/bin/with-contenv sh

# Install the version of PRT present on the master node
DISTRIBUTE_SINGLE_TRANSCODES="$(s6-setuidgid plex ssh $(echo ${MASTER_IP} | sed 's/"//g') 'cat /var/run/s6/container_environment/DISTRIBUTE_SINGLE_TRANSCODES')"
if [ "${DISTRIBUTE_SINGLE_TRANSCODES}" = true ]; then
	cd /app/prt-JJK801/Plex-Remote-Transcoder-master
else
	cd /app/prt-wnielson/Plex-Remote-Transcoder-master
fi
python setup.py install

# Register with the master node
s6-setuidgid plex ssh -tt $(echo ${MASTER_IP} | sed 's/"//g') <<-EOF

	### Variables
	SLAVE_IP=\$(echo \$SSH_CLIENT | awk '{print \$1}')

	### Set the master IP in the PRT configuration
	echo ${MASTER_IP} | prt install

	### Register with PRT
	echo 'y' | prt add_host \${SLAVE_IP} ${SLAVE_SSH_PORT} plex

	### Register with Plex (allowed networks)
	# Get the list of Plex allowed networks
	plex_allowed_networks=\$(xmlstarlet sel -T -t -m "/Preferences" -v @allowedNetworks -n "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Preferences.xml")

	# Check that the slave IP is not already a Plex allowed network
	if ! echo "\${plex_allowed_networks}" | grep -q "\${SLAVE_IP}"; then

		# Generate updated list
		if [ -z "\$plex_allowed_networks" ]; then
			plex_allowed_networks="\${SLAVE_IP}"
		else
			plex_allowed_networks="\${plex_allowed_networks},\${SLAVE_IP}"
		fi

		# Apply the updated list
		xmlstarlet ed --inplace --update "/Preferences/@allowedNetworks" -v "\${plex_allowed_networks}" "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Preferences.xml"

	fi

	### Register with SSH ControlMaster
	if [ -e /config/.ssh/config ]; then
		# Reset SSH settings set for this slave node
		sed -i '/^Host '"\${SLAVE_IP}"'/,/^Host /{//!d}' /config/.ssh/config
		sed -i "/^Host \${SLAVE_IP}/d" /config/.ssh/config
		# Add a new line at the end of the config file only if it doesn’t already end with one
		sed -i -e '\$a\' /config/.ssh/config
	fi
	printf "Host \${SLAVE_IP}\n        User plex\n        Port \$(echo ${SLAVE_SSH_PORT} | sed 's/\"//g')\n        ControlPath /config/.ssh/controlmasters/%%r@%%h:%%p\n        ControlMaster auto\n        ControlPersist 2h\n        StrictHostKeyChecking no\n" >> /config/.ssh/config

	exit

EOF